% function [gait_parameters_combined,loading_stance,early_stance,mid_stance,late_stance,full_stance,ROM] =...
%     stats_table_no_emg_mean(gait_metrics_mean,...
%     main_parameters_mean,participant_number)
function [gait_parameters_combined,loading_stance,early_stance,mid_stance,late_stance,full_stance,ROM,more_severe,less_severe] =...
    stats_table_no_emg_mean(gait_metrics_mean,...
    main_parameters_mean,participant_number,trial_name,severe,folder)

conditions = {'control', 'keeogo'};
more_severe = struct();
less_severe = struct();
for i = 1:length(conditions)
    if severe == 1
        for fn = fieldnames(gait_metrics_mean.(conditions{i}).left)'
            more_severe.(conditions{i}).(fn{1}) = gait_metrics_mean.(conditions{i}).left.(fn{1});
            less_severe.(conditions{i}).(fn{1}) = gait_metrics_mean.(conditions{i}).right.(fn{1});
        end
        
        % Copy fields from the second structure
        for fn = fieldnames(main_parameters_mean.(conditions{i}).left)'
            more_severe.(conditions{i}).(fn{1}) = main_parameters_mean.(conditions{i}).left.(fn{1});
            less_severe.(conditions{i}).(fn{1}) = main_parameters_mean.(conditions{i}).right.(fn{1});
        end
    else
        for fn = fieldnames(gait_metrics_mean.(conditions{i}).left)'
            more_severe.(conditions{i}).(fn{1}) = gait_metrics_mean.(conditions{i}).right.(fn{1});
            less_severe.(conditions{i}).(fn{1}) = gait_metrics_mean.(conditions{i}).left.(fn{1});
        end
        
        % Copy fields from the second structure
        for fn = fieldnames(main_parameters_mean.(conditions{i}).left)'
            more_severe.(conditions{i}).(fn{1}) = main_parameters_mean.(conditions{i}).right.(fn{1});
            less_severe.(conditions{i}).(fn{1}) = main_parameters_mean.(conditions{i}).left.(fn{1});
        end
    end
end

% 0 = control
% 1 = keeogo
% % Define the gait parameters and their respective names
params = {'stride_length', 'stride_time', 'stancetime', 'swingtime', ...
    'stance_perc', 'swing_perc', 'toe_out', 'step_width', 'step_length', 'single_support'};
param_names = {'stride_length', 'stride_time', 'stance_time', 'swing_time', ...
    'stance_percent', 'swing_percent', 'toe_angle', 'step_width', 'step_length', 'single_support'};


%%
% 
% % Create tables for each gait parameter
% for i = 1:length(params\
%     param_name = params{i};
%     tbl_name = param_names{i};
%     gait_parameters_combined.(tbl_name) = createGaitParameterTable(gait_metrics_mean, param_name);
% end
% % Define a function to create tables for each parameter
% function tbl = createGaitParameterTable(metrics, param_name)
%     conditions = {
%         'Control More Severe', 'Keeogo More Severe', ...
%         'Control Less Severe', 'Keeogo Less Severe', ...
%         'Total Control', 'Total Keeogo'};
% 
%     sides = {'left', 'left', 'right', 'right', 'total', 'total'};
%     devices = {'control', 'keeogo', 'control', 'keeogo', 'control', 'keeogo'};
% 
%     data = cell(length(conditions), 3);
%     for i = 1:length(conditions)
%         mean_value = metrics.(devices{i}).(sides{i}).(param_name).mean;
%         std_value = metrics.(devices{i}).(sides{i}).(param_name).std;
%         data{i, 1} = [conditions{i} ' ' strrep(param_name, '_', ' ')];
%         data{i, 2} = mean_value;
%         data{i, 3} = std_value;
%     end
% 
%     tbl = cell2table(data, "VariableNames", {'Condition', 'Mean', 'STD'});
% end

% %%
% 
% parameters = {'stride_length', 'stride_time', 'stance_time', 'swing_time', ...
%     'stance_percent', 'swing_percent', 'toe_angle', 'step_width', 'step_length', 'single_support', 'speed'};
% 
% for parameter = parameters
%     gait_parameters_combined = createTable(gait_parameters_combined, gait_metrics_mean, parameter);
% end
% 
% function gait_parameters_combined = createTable(gait_parameters_combined, gait_metrics_mean, parameter)
%     conditions = {'Control More Severe', 'Keeogo More Severe', 'Control Less Severe', 'Keeogo Less Severe', 'Total Control', 'Total Keeogo'};
%     gait_parameters_combined.(parameter) = cell2table(cellfun(@(x) {sprintf('%s %s', x, parameter), ...
%         gait_metrics_mean.(lower(strsplit(x, ' '){2})).(lower(strsplit(x, ' '){1})).(parameter).mean, ...
%         gait_metrics_mean.(lower(strsplit(x, ' '){2})).(lower(strsplit(x, ' '){1})).(parameter).std}, conditions), ...
%         "VariableNames", {'Condition', 'Mean', 'STD'});
% end

%% Add Values into a table
%% Stride Length
gait_parameters_combined.stride_length = {'Control More Severe Stride',more_severe.control.stride_length.mean, more_severe.control.stride_length.std;...
    'Keeogo More Severe Stride',more_severe.keeogo.stride_length.mean, more_severe.keeogo.stride_length.std;...
    'Control Less Severe Stride',less_severe.control.stride_length.mean, less_severe.control.stride_length.std;...
    'Keeogo Less Severe Stride',less_severe.keeogo.stride_length.mean, less_severe.keeogo.stride_length.std;...
    'Total Control Severe Stride', gait_metrics_mean.control.total.stride_length.mean, gait_metrics_mean.control.total.stride_length.std;...
    'Total Keeogo Severe Stride', gait_metrics_mean.keeogo.total.stride_length.mean, gait_metrics_mean.keeogo.total.stride_length.std};
gait_parameters_combined.stride_length = cell2table(gait_parameters_combined.stride_length,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.stride_time = {'Control More Severe Stride Time',more_severe.control.stride_time.mean, more_severe.control.stride_time.std;...
    'Keeogo More Severe Stride Time',more_severe.keeogo.stride_time.mean, more_severe.keeogo.stride_time.std;...
    'Control Less Severe Stride Time',less_severe.control.stride_time.mean, less_severe.control.stride_time.std;...
    'Keeogo Less Severe Stride Time',less_severe.keeogo.stride_time.mean, less_severe.keeogo.stride_time.std;...
    'Total Control Stride Time', gait_metrics_mean.control.total.stride_time.mean, gait_metrics_mean.control.total.stride_time.std;...
    'Total Keeogo Stride Time', gait_metrics_mean.keeogo.total.stride_time.mean, gait_metrics_mean.keeogo.total.stride_time.std};
gait_parameters_combined.stride_time = cell2table(gait_parameters_combined.stride_time,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.stance_time = {'Control More Severe Stance Time',more_severe.control.stancetime.mean, more_severe.control.stancetime.std;...
    'Keeogo More Severe Stance Time',more_severe.keeogo.stancetime.mean, more_severe.keeogo.stancetime.std;...
    'Control Less Severe Stance Time',less_severe.control.stancetime.mean, less_severe.control.stancetime.std;...
    'Keeogo Less Severe Stance Time',less_severe.keeogo.stancetime.mean, less_severe.keeogo.stancetime.std;...
    'Total Control Stance Time', gait_metrics_mean.control.total.stancetime.mean, gait_metrics_mean.control.total.stancetime.std;...
    'Total Keeogo Stance Time', gait_metrics_mean.keeogo.total.stancetime.mean, gait_metrics_mean.keeogo.total.stancetime.std};
gait_parameters_combined.stance_time = cell2table(gait_parameters_combined.stance_time,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.swing_time = {'Control More Severe Swing Time',more_severe.control.swingtime.mean, more_severe.control.swingtime.std;...
    'Keeogo More Severe Swing Time',more_severe.keeogo.swingtime.mean, more_severe.keeogo.swingtime.std;...
    'Control Less Severe Swing Time',less_severe.control.swingtime.mean, less_severe.control.swingtime.std;...
    'Keeogo Less Severe Swing Time',less_severe.keeogo.swingtime.mean, less_severe.keeogo.swingtime.std;...
    'Total Control Swing Time', gait_metrics_mean.control.total.swingtime.mean, gait_metrics_mean.control.total.swingtime.std;...
    'Total Keeogo Swing Time', gait_metrics_mean.keeogo.total.swingtime.mean, gait_metrics_mean.keeogo.total.swingtime.std};
gait_parameters_combined.swing_time = cell2table(gait_parameters_combined.swing_time,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.stance_percent = {'Control More Severe Stance Percent',more_severe.control.stance_perc.mean, more_severe.control.stance_perc.std;...
    'Keeogo More Severe Stance Percent',more_severe.keeogo.stance_perc.mean, more_severe.keeogo.stance_perc.std;...
    'Control Less Severe Stance Percent',less_severe.control.stance_perc.mean, less_severe.control.stance_perc.std;...
    'Keeogo Less Severe Stance Percent',less_severe.keeogo.stance_perc.mean, less_severe.keeogo.stance_perc.std;...
    'Total Control Stance Percent', gait_metrics_mean.control.total.stance_perc.mean, gait_metrics_mean.control.total.stance_perc.std;...
    'Total Keeogo Stance Percent', gait_metrics_mean.keeogo.total.stance_perc.mean, gait_metrics_mean.keeogo.total.stance_perc.std};
gait_parameters_combined.stance_percent = cell2table(gait_parameters_combined.stance_percent,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.swing_percent = {'Control More Severe Swing Percent',more_severe.control.swing_perc.mean, more_severe.control.swing_perc.std;...
    'Keeogo More Severe Swing Percent',more_severe.keeogo.swing_perc.mean, more_severe.keeogo.swing_perc.std;...
    'Control Less Severe Swing Percent',less_severe.control.swing_perc.mean, less_severe.control.swing_perc.std;...
    'Keeogo Less Severe Swing Percent',less_severe.keeogo.swing_perc.mean, less_severe.keeogo.swing_perc.std;...
    'Total Control Swing Percent', gait_metrics_mean.control.total.swing_perc.mean, gait_metrics_mean.control.total.swing_perc.std;...
    'Total Keeogo Swing Percent', gait_metrics_mean.keeogo.total.swing_perc.mean, gait_metrics_mean.keeogo.total.swing_perc.std};
gait_parameters_combined.swing_percent = cell2table(gait_parameters_combined.swing_percent,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.toe_angle = {'Control More Severe Toe Angle',more_severe.control.toe_out.mean, more_severe.control.toe_out.std;...
    'Keeogo More Severe Toe Angle',more_severe.keeogo.toe_out.mean, more_severe.keeogo.toe_out.std;...
    'Control Less Severe Toe Angle',less_severe.control.toe_out.mean, less_severe.control.toe_out.std;...
    'Keeogo Less Severe Toe Angle',less_severe.keeogo.toe_out.mean, less_severe.keeogo.toe_out.std;...
    'Total Control Toe Angle', gait_metrics_mean.control.total.toe_out.mean, gait_metrics_mean.control.total.toe_out.std;...
    'Total Keeogo Toe Angle', gait_metrics_mean.keeogo.total.toe_out.mean, gait_metrics_mean.keeogo.total.toe_out.std};
gait_parameters_combined.toe_angle = cell2table(gait_parameters_combined.toe_angle,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.step_width = {'Control More Severe Step Width',more_severe.control.step_width.mean, more_severe.control.step_width.std;...
    'Keeogo More Severe Step Width',more_severe.keeogo.step_width.mean, more_severe.keeogo.step_width.std;...
    'Control Less Severe Step Width',less_severe.control.step_width.mean, less_severe.control.step_width.std;...
    'Keeogo Less Severe Step Width',less_severe.keeogo.step_width.mean, less_severe.keeogo.step_width.std;...
    'Total Control Step Width', gait_metrics_mean.control.total.step_width.mean, gait_metrics_mean.control.total.step_width.std;...
    'Total Keeogo Step Width', gait_metrics_mean.keeogo.total.step_width.mean, gait_metrics_mean.keeogo.total.step_width.std};
gait_parameters_combined.step_width = cell2table(gait_parameters_combined.step_width,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.step_length = {'Control More Severe Step Length',more_severe.control.step_length.mean, more_severe.control.step_length.std;...
    'Keeogo More Severe Step Length',more_severe.keeogo.step_length.mean, more_severe.keeogo.step_length.std;...
    'Control Less Severe Step Length',less_severe.control.step_length.mean, less_severe.control.step_length.std;...
    'Keeogo Less Severe Step Length',less_severe.keeogo.step_length.mean, less_severe.keeogo.step_length.std;...
    'Total Control Step Length', gait_metrics_mean.control.total.step_length.mean, gait_metrics_mean.control.total.step_length.std;...
    'Total Keeogo Step Length', gait_metrics_mean.keeogo.total.step_length.mean, gait_metrics_mean.keeogo.total.step_length.std};
gait_parameters_combined.step_length = cell2table(gait_parameters_combined.step_length,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.single_support = {'Control More Severe Single Support',more_severe.control.single_support.mean, more_severe.control.single_support.std;...
    'Keeogo More Severe Single Support',more_severe.keeogo.single_support.mean, more_severe.keeogo.single_support.std;...
    'Control Less Severe Single Support',less_severe.control.single_support.mean, less_severe.control.single_support.std;...
    'Keeogo Less Severe Single Support',less_severe.keeogo.single_support.mean, less_severe.keeogo.single_support.std;...
    'Total Control Single Support', gait_metrics_mean.control.total.single_support.mean, gait_metrics_mean.control.total.single_support.std;...
    'Total Keeogo Single Support', gait_metrics_mean.keeogo.total.single_support.mean, gait_metrics_mean.keeogo.total.single_support.std};
gait_parameters_combined.single_support = cell2table(gait_parameters_combined.single_support,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.speed = {'Control Speed',gait_metrics_mean.control.total.speed.mean, gait_metrics_mean.control.total.speed.std;...
    'Keeogo Speed',gait_metrics_mean.keeogo.total.speed.mean, gait_metrics_mean.keeogo.total.speed.std};
gait_parameters_combined.speed = cell2table(gait_parameters_combined.speed,"VariableNames",{'Condition','Mean','STD'});
% %% CCI
% %loading Stance
% loading_stance.CCI = {'Control More Severe Loading CCI',gait_emg_metrics_combined1_rms.control.CCI_l_loading_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_loading_rms.std;...
%     'Keeogo More Severe Loading CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_loading_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_loading_rms.std;...
%     'Control Less Severe Loading CCI',gait_emg_metrics_combined1_rms.control.CCI_r_loading_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_loading_rms.std;...
%     'Keeogo Less Severe Loading CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_loading_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_loading_rms.std};
% loading_stance.CCI = cell2table(loading_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %Early Stance
% early_stance.CCI = {'Control More Severe Early CCI',gait_emg_metrics_combined1_rms.control.CCI_l_early_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_early_rms.std;...
%     'Keeogo More Severe Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_early_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_early_rms.std;...
%     'Control Less Severe Early CCI',gait_emg_metrics_combined1_rms.control.CCI_r_early_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_early_rms.std;...
%     'Keeogo Less Severe Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_early_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_early_rms.std};
% early_stance.CCI = cell2table(early_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %Mid Stance
% mid_stance.CCI = {'Control More Severe Early CCI',gait_emg_metrics_combined1_rms.control.CCI_l_mid_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_mid_rms.std;...
%     'Keeogo More Severe Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_mid_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_mid_rms.std;...
%     'Control Less Severe Early CCI',gait_emg_metrics_combined1_rms.control.CCI_r_mid_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_mid_rms.std;...
%     'Keeogo Less Severe Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_mid_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_mid_rms.std};
% mid_stance.CCI = cell2table(mid_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %Late Stance
% late_stance.CCI = {'Control More Severe Early CCI',gait_emg_metrics_combined1_rms.control.CCI_l_late_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_late_rms.std;...
%     'Keeogo More Severe Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_late_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_late_rms.std;...
%     'Control Less Severe Early CCI',gait_emg_metrics_combined1_rms.control.CCI_r_late_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_late_rms.std;...
%     'Keeogo Less Severe Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_late_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_late_rms.std};
% late_stance.CCI = cell2table(late_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %% CCR Zero
% %loading Stance
% loading_stance.CCR = {'Control More Severe Loading CCI',gait_emg_metrics_combined1.control.CCR_zero_l_loading.mean,gait_emg_metrics_combined1.control.CCR_zero_l_loading.std;...
%     'Keeogo More Severe Loading CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_loading.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_loading.std;...
%     'Control Less Severe Loading CCI',gait_emg_metrics_combined1.control.CCR_zero_r_loading.mean,gait_emg_metrics_combined1.control.CCR_zero_r_loading.std;...
%     'Keeogo Less Severe Loading CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_loading.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_loading.std};
% loading_stance.CCR = cell2table(loading_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %Early Stance
% early_stance.CCR = {'Control More Severe Early CCI',gait_emg_metrics_combined1.control.CCR_zero_l_early.mean,gait_emg_metrics_combined1.control.CCR_zero_l_early.std;...
%     'Keeogo More Severe Early CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_early.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_early.std;...
%     'Control Less Severe Early CCI',gait_emg_metrics_combined1.control.CCR_zero_r_early.mean,gait_emg_metrics_combined1.control.CCR_zero_r_early.std;...
%     'Keeogo Less Severe Early CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_early.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_early.std};
% early_stance.CCR = cell2table(early_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %Mid Stance
% mid_stance.CCR = {'Control More Severe Mid CCI',gait_emg_metrics_combined1.control.CCR_zero_l_mid.mean,gait_emg_metrics_combined1.control.CCR_zero_l_mid.std;...
%     'Keeogo More Severe Mid CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_mid.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_mid.std;...
%     'Control Less Severe Mid CCI',gait_emg_metrics_combined1.control.CCR_zero_r_mid.mean,gait_emg_metrics_combined1.control.CCR_zero_r_mid.std;...
%     'Keeogo Less Severe Mid CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_mid.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_mid.std};
% mid_stance.CCR = cell2table(mid_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %Late Stance
% late_stance.CCR = {'Control More Severe Late CCI',gait_emg_metrics_combined1.control.CCR_zero_l_late.mean,gait_emg_metrics_combined1.control.CCR_zero_l_late.std;...
%     'Keeogo More Severe Late CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_late.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_late.std;...
%     'Control Less Severe Late CCI',gait_emg_metrics_combined1.control.CCR_zero_r_late.mean,gait_emg_metrics_combined1.control.CCR_zero_r_late.std;...
%     'Keeogo Less Severe Late CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_late.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_late.std};
% late_stance.CCR = cell2table(late_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %% Swing
% %Swing Full
% swing.full_quadriceps =  {'Control More Severe Quadricep Swing',gait_emg_swing_metrics_combined.control.lquad_swing.mean,gait_emg_swing_metrics_combined.control.lquad_swing.std;...
%     'Keeogo More Severe Quadricep Swing',gait_emg_swing_metrics_combined.keeogo.lquad_swing.mean,gait_emg_swing_metrics_combined.keeogo.lquad_swing.std;...
%     'Control Less Severe Quadricep Swing',gait_emg_swing_metrics_combined.control.rquad_swing.mean,gait_emg_swing_metrics_combined.control.rquad_swing.std;...
%     'Keeogo Less Severe Quadricep Swing',gait_emg_swing_metrics_combined.keeogo.rquad_swing.mean,gait_emg_swing_metrics_combined.keeogo.rquad_swing.std};
% swing.full_quadriceps = cell2table(swing.full_quadriceps,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.full_hamstrings =  {'Control More Severe Hamstring Swing',gait_emg_swing_metrics_combined.control.lham_swing.mean,gait_emg_swing_metrics_combined.control.lham_swing.std;...
%     'Keeogo More Severe Hamstring Swing',gait_emg_swing_metrics_combined.keeogo.lham_swing.mean,gait_emg_swing_metrics_combined.keeogo.lham_swing.std;...
%     'Control Less Severe Hamstring Swing',gait_emg_swing_metrics_combined.control.rham_swing.mean,gait_emg_swing_metrics_combined.control.rham_swing.std;...
%     'Keeogo Less Severe Hamstring Swing',gait_emg_swing_metrics_combined.keeogo.rham_swing.mean,gait_emg_swing_metrics_combined.keeogo.rham_swing.std};
% swing.full_hamstrings = cell2table(swing.full_hamstrings,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.full_gastrocnemius =  {'Control More Severe Gastrocnemius Swing',gait_emg_swing_metrics_combined.control.lgas_swing.mean,gait_emg_swing_metrics_combined.control.lgas_swing.std;...
%     'Keeogo More Severe Gastrocnemius Swing',gait_emg_swing_metrics_combined.keeogo.lgas_swing.mean,gait_emg_swing_metrics_combined.keeogo.lgas_swing.std;...
%     'Control Less Severe Gastrocnemius Swing',gait_emg_swing_metrics_combined.control.rgas_swing.mean,gait_emg_swing_metrics_combined.control.rgas_swing.std;...
%     'Keeogo Less Severe Gastrocnemius Swing',gait_emg_swing_metrics_combined.keeogo.rgas_swing.mean,gait_emg_swing_metrics_combined.keeogo.rgas_swing.std};
% swing.full_gastrocnemius = cell2table(swing.full_gastrocnemius,"VariableNames",{'Condition','Mean','STD'});
% 
% % Swing Prep
% swing.prep_quadriceps =  {'Control More Severe Quadricep Prep Swing',gait_emg_swing_metrics_combined.control.lquad_stride_prep.mean,gait_emg_swing_metrics_combined.control.lquad_stride_prep.std;...
%     'Keeogo More Severe Quadricep Prep Swing',gait_emg_swing_metrics_combined.keeogo.lquad_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.lquad_stride_prep.std;...
%     'Control Less Severe Quadricep Prep Swing',gait_emg_swing_metrics_combined.control.rquad_stride_prep.mean,gait_emg_swing_metrics_combined.control.rquad_stride_prep.std;...
%     'Keeogo Less Severe Quadricep Prep Swing',gait_emg_swing_metrics_combined.keeogo.rquad_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.rquad_stride_prep.std};
% swing.prep_quadriceps = cell2table(swing.prep_quadriceps,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.prep_hamstrings =  {'Control More Severe Hamstring Prep Swing',gait_emg_swing_metrics_combined.control.lham_stride_prep.mean,gait_emg_swing_metrics_combined.control.lham_stride_prep.std;...
%     'Keeogo More Severe Hamstring Prep Swing',gait_emg_swing_metrics_combined.keeogo.lham_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.lham_stride_prep.std;...
%     'Control Less Severe Hamstring Prep Swing',gait_emg_swing_metrics_combined.control.rham_stride_prep.mean,gait_emg_swing_metrics_combined.control.rham_stride_prep.std;...
%     'Keeogo Less Severe Hamstring Prep Swing',gait_emg_swing_metrics_combined.keeogo.rham_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.rham_stride_prep.std};
% swing.prep_hamstrings = cell2table(swing.prep_hamstrings,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.prep_gastrocnemius =  {'Control More Severe Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.control.lgas_stride_prep.mean,gait_emg_swing_metrics_combined.control.lgas_stride_prep.std;...
%     'Keeogo More Severe Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.keeogo.lgas_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.lgas_stride_prep.std;...
%     'Control Less Severe Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.control.rgas_stride_prep.mean,gait_emg_swing_metrics_combined.control.rgas_stride_prep.std;...
%     'Keeogo Less Severe Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.keeogo.rgas_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.rgas_stride_prep.std};
% swing.prep_gastrocnemius = cell2table(swing.prep_gastrocnemius,"VariableNames",{'Condition','Mean','STD'});
%% Range of motion
ROM = {'Control More Severe ROM Left', more_severe.control.swing_rom.mean, more_severe.control.swing_rom.std;...
    'Keeogo More Severe ROM Left', more_severe.keeogo.swing_rom.mean, more_severe.keeogo.swing_rom.std;...
    'Control Less Severe ROM Right', less_severe.control.swing_rom.mean, less_severe.control.swing_rom.std;...
    'Keeogo Less Severe ROM Right', less_severe.keeogo.swing_rom.mean, less_severe.keeogo.swing_rom.std};
ROM = cell2table(ROM,"VariableNames",{'Condition','Mean','STD'});
%% Moments
%loading Stance
loading_stance.flexion = {'Control More Severe Loading Flexion',more_severe.control.loading_stance.flexion.mean, more_severe.control.loading_stance.flexion.std;...
    'Keeogo More Severe Loading Flexion',more_severe.keeogo.loading_stance.flexion.mean, more_severe.keeogo.loading_stance.flexion.std;...
    'Control Less Severe Loading Flexion',less_severe.control.loading_stance.flexion.mean, less_severe.control.loading_stance.flexion.std;...
    'Keeogo Less Severe Loading Flexion',less_severe.keeogo.loading_stance.flexion.mean, less_severe.keeogo.loading_stance.flexion.std};
loading_stance.flexion = cell2table(loading_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

loading_stance.adduction = {'Control More Severe Loading Adduction',more_severe.control.loading_stance.adduction.mean,more_severe.control.loading_stance.adduction.std;...
    'Keeogo More Severe Loading Adduction',more_severe.keeogo.loading_stance.adduction.mean,more_severe.keeogo.loading_stance.adduction.std;...
    'Control Less Severe Loading Adduction',less_severe.control.loading_stance.adduction.mean, less_severe.control.loading_stance.adduction.std;...
    'Keeogo Less Severe Loading Adduction',less_severe.keeogo.loading_stance.adduction.mean, less_severe.keeogo.loading_stance.adduction.std};
loading_stance.adduction = cell2table(loading_stance.adduction,"VariableNames",{'Condition','Mean','STD'});
%early Stance
early_stance.flexion = {'Control More Severe Early Flexion', more_severe.control.early_stance.flexion.mean,more_severe.control.early_stance.flexion.std;...
    'Keeogo More Severe Early Flexion', more_severe.keeogo.early_stance.flexion.mean, more_severe.keeogo.early_stance.flexion.std;...
    'Control Less Severe Early Flexion', less_severe.control.early_stance.flexion.mean,less_severe.control.early_stance.flexion.std;...
    'Keeogo Less Severe Early Flexion', less_severe.keeogo.early_stance.flexion.mean, less_severe.keeogo.early_stance.flexion.std};
early_stance.flexion = cell2table(early_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

early_stance.adduction = {'Control More Severe Early Adduction', more_severe.control.early_stance.adduction.mean,more_severe.control.early_stance.adduction.std;...
    'Keeogo More Severe Early Adduction', more_severe.keeogo.early_stance.adduction.mean, more_severe.keeogo.early_stance.adduction.std;...
    'Control Less Severe Early Adduction', less_severe.control.early_stance.adduction.mean,less_severe.control.early_stance.adduction.std;...
    'Keeogo Less Severe Early Adduction', less_severe.keeogo.early_stance.adduction.mean, less_severe.keeogo.early_stance.adduction.std};
early_stance.adduction = cell2table(early_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%Mid-stance 
mid_stance.flexion = {'Control More Severe Mid Flexion', more_severe.control.mid_stance.flexion.mean,more_severe.control.mid_stance.flexion.std;...
    'Keeogo More Severe Mid Flexion', more_severe.keeogo.mid_stance.flexion.mean, more_severe.keeogo.mid_stance.flexion.std;...
    'Control Less Severe Mid Flexion', less_severe.control.mid_stance.flexion.mean,less_severe.control.mid_stance.flexion.std;...
    'Keeogo Less Severe Mid Flexion', less_severe.keeogo.mid_stance.flexion.mean, less_severe.keeogo.mid_stance.flexion.std};
mid_stance.flexion = cell2table(mid_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

mid_stance.adduction = {'Control More Severe Mid Adduction',more_severe.control.mid_stance.adduction.mean,more_severe.control.mid_stance.adduction.std;...
    'Keeogo More Severe Mid Adduction',more_severe.keeogo.mid_stance.adduction.mean, more_severe.keeogo.mid_stance.adduction.std;...
    'Control Less Severe Mid Adduction',less_severe.control.mid_stance.adduction.mean,less_severe.control.mid_stance.adduction.std;...
    'Keeogo Less Severe Mid Adduction',less_severe.keeogo.mid_stance.adduction.mean, less_severe.keeogo.mid_stance.adduction.std};
mid_stance.adduction = cell2table(mid_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%late Stance
late_stance.flexion = {'Control More Severe Late Flexion',more_severe.control.late_stance.flexion.mean,more_severe.control.late_stance.flexion.std;...
    'Keeogo More Severe Late Flexion',more_severe.keeogo.late_stance.flexion.mean, more_severe.keeogo.late_stance.flexion.std;...
    'Control Less Severe Late Flexion', less_severe.control.late_stance.flexion.mean,less_severe.control.late_stance.flexion.std;...
    'Keeogo Less Severe Late Flexion',less_severe.keeogo.late_stance.flexion.mean, less_severe.keeogo.late_stance.flexion.std};
late_stance.flexion = cell2table(late_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

late_stance.adduction = {'Control More Severe Late Adduction',more_severe.control.late_stance.adduction.mean,more_severe.control.late_stance.adduction.std;...
    'Keeogo More Severe Late Adduction',more_severe.keeogo.late_stance.adduction.mean, more_severe.keeogo.late_stance.adduction.std;...
    'Control Less Severe Late Adduction',less_severe.control.late_stance.adduction.mean, less_severe.control.late_stance.adduction.std;...
    'Keeogo Less Severe Late Adduction',less_severe.keeogo.late_stance.adduction.mean, less_severe.keeogo.late_stance.adduction.std};
late_stance.adduction = cell2table(late_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%full Stance
full_stance.flexion = {'Control More Severe Full Flexion',more_severe.control.full_stance.flexion.mean,more_severe.control.full_stance.flexion.std;...
    'Keeogo More Severe Full Flexion',more_severe.keeogo.full_stance.flexion.mean, more_severe.keeogo.full_stance.flexion.std;...
    'Control Less Severe Full Flexion',less_severe.control.full_stance.flexion.mean,less_severe.control.full_stance.flexion.std;...
    'Keeogo Less Severe Full Flexion',less_severe.keeogo.full_stance.flexion.mean, less_severe.keeogo.full_stance.flexion.std};
full_stance.flexion = cell2table(full_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

full_stance.adduction = {'Control More Severe Full Adduction',more_severe.control.full_stance.adduction.mean,more_severe.control.full_stance.adduction.std;...
    'Keeogo More Severe Full Adduction', more_severe.keeogo.full_stance.adduction.mean, more_severe.keeogo.full_stance.adduction.std;...
    'Control Less Severe Full Adduction', less_severe.control.full_stance.adduction.mean, less_severe.control.full_stance.adduction.std;...
    'Keeogo Less Severe Full Adduction', less_severe.keeogo.full_stance.adduction.mean, less_severe.keeogo.full_stance.adduction.std};
full_stance.adduction = cell2table(full_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File name
if contains(lower(trial_name{1}),'neutral')
    name = 'neutral';
elseif contains(lower(trial_name{1}),'uphill')
    name = 'uphill';
elseif contains(lower(trial_name{1}),'downhill')
    name = 'downhill';
end

% Create Unique File name
file_name = 'stats_analysis_'+ participant_number + '_' + name + '.xlsx';
% Creating a folder for Excel files

if ~exist(folder, 'dir')
    mkdir(folder);
end

% Storing the excel files in a specific Folder
excel_file = fullfile(folder,file_name);
%% Stride Length
writetable(gait_parameters_combined.stride_length,excel_file,'Sheet','stride_length','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.stride_time,excel_file,'Sheet','stride_time','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.stance_time,excel_file,'Sheet','stance_time','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.swing_time,excel_file,'Sheet','swing_time','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.stance_percent,excel_file,'Sheet','stance_percent','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.swing_percent,excel_file,'Sheet','swing_percent','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.toe_angle,excel_file,'Sheet','toe_angle','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.step_width,excel_file,'Sheet','step_width','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.step_length,excel_file,'Sheet','step_length','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.single_support,excel_file,'Sheet','single_support','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.speed,excel_file,'Sheet','speed','WriteVariableNames',true,'Range','B1');
%% ROM
writetable(ROM,excel_file,'Sheet','ROM','WriteVariableNames',true,'Range','B1');

% %% CCI
% writetable(loading_stance.CCI,excel_file,'Sheet','CCI','WriteVariableNames',true,'Range','B1')
% writetable(early_stance.CCI,excel_file,'Sheet','CCI','WriteVariableNames',true,'Range','B6')
% writetable(mid_stance.CCI,excel_file,'Sheet','CCI','WriteVariableNames',true,'Range','B11')
% writetable(late_stance.CCI,excel_file,'Sheet','CCI','WriteVariableNames',true,'Range','B16')
% %% CCR
% writetable(loading_stance.CCR,excel_file,'Sheet','CCR','WriteVariableNames',true,'Range','B1')
% writetable(early_stance.CCR,excel_file,'Sheet','CCR','WriteVariableNames',true,'Range','B6')
% writetable(mid_stance.CCR,excel_file,'Sheet','CCR','WriteVariableNames',true,'Range','B11')
% writetable(late_stance.CCR,excel_file,'Sheet','CCR','WriteVariableNames',true,'Range','B16')
% %% Swing
% writetable(swing.full_quadriceps,excel_file,'Sheet','Swing_Full','WriteVariableNames',true,'Range','B1')
% writetable(swing.full_hamstring,excel_file,'Sheet','Swing_Full','WriteVariableNames',true,'Range','B6')
% writetable(swing.full_gastrocnemius,excel_file,'Sheet','Swing_Full','WriteVariableNames',true,'Range','B11')
% writetable(swing.prep_quadriceps,excel_file,'Sheet','Swing_Prep','WriteVariableNames',true,'Range','B16')
% writetable(swing.prep_hamstring,excel_file,'Sheet','Swing_Prep','WriteVariableNames',true,'Range','B21')
% writetable(swing.prep_gastrocnemius,excel_file,'Sheet','Swing_Prep','WriteVariableNames',true,'Range','B26')
%% Moments (Flexion)
%Loading
writetable(loading_stance.flexion,excel_file,'Sheet','Loading_Flexion','WriteVariableNames',true,'Range','B1');
%Early
writetable(early_stance.flexion,excel_file,'Sheet','Early_Flexion','WriteVariableNames',true,'Range','B1');
%Mid
writetable(mid_stance.flexion,excel_file,'Sheet','Mid_Flexion','WriteVariableNames',true,'Range','B1');

%Late
writetable(late_stance.flexion,excel_file,'Sheet','Late_Flexion','WriteVariableNames',true,'Range','B1');

%Full
writetable(full_stance.flexion,excel_file,'Sheet','Full_Flexion','WriteVariableNames',true,'Range','B1');

%% Moments (Adduction)
%Loading
writetable(loading_stance.adduction,excel_file,'Sheet','Loading_Adduction','WriteVariableNames',true,'Range','B1');

%Early
writetable(early_stance.adduction,excel_file,'Sheet','Early_Adduction','WriteVariableNames',true,'Range','B1');

%Mid
writetable(mid_stance.adduction,excel_file,'Sheet','Mid_Adduction','WriteVariableNames',true,'Range','B1');

%Late
writetable(late_stance.adduction,excel_file,'Sheet','Late_Adduction','WriteVariableNames',true,'Range','B1');

%Full
writetable(full_stance.adduction,excel_file,'Sheet','Full_Adduction','WriteVariableNames',true,'Range','B1');

%%

end