% function [gait_parameters_combined,loading_stance,early_stance,mid_stance,late_stance,full_stance,ROM] =...
%     stats_table_no_emg_mean(gait_metrics_mean,...
%     main_parameters_mean,participant_number)
function [gait_parameters_combined,loading_stance,early_stance,mid_stance,late_stance,full_stance,ROM,swing] =...
    stats_table_no_emg(gait_metrics_mean,...
    main_parameters_mean,participant_number)
% function [stride_length,loading_stance,mid_stance,late_stance,ROM] =...
%     stats_table(gait_emg_metrics,main_parameters_full,participant_number)
% function [loading_stance,early_stance,mid_stance,late_stance,combined] =...
%     stats_table(gait_emg_metrics,gait_emg_metrics_rms,participant_number)

% 0 = control
% 1 = keeogo
% % Define the gait parameters and their respective names
% params = {'stride_length', 'stride_time', 'stancetime', 'swingtime', ...
%     'stance_perc', 'swing_perc', 'toe_out', 'step_width', 'step_length', 'single_support'};
% param_names = {'stride_length', 'stride_time', 'stance_time', 'swing_time', ...
%     'stance_percent', 'swing_percent', 'toe_angle', 'step_width', 'step_length', 'single_support'};
% 
% % Create tables for each gait parameter
% for i = 1:length(params)
%     param_name = params{i};
%     tbl_name = param_names{i};
%     gait_parameters_combined.(tbl_name) = createGaitParameterTable(gait_metrics_mean, param_name);
% end
% % Define a function to create tables for each parameter
% function tbl = createGaitParameterTable(metrics, param_name)
%     conditions = {
%         'Control Left', 'Keeogo Left', ...
%         'Control Right', 'Keeogo Right', ...
%         'Total Control', 'Total Keeogo'};
% 
%     sides = {'left', 'left', 'right', 'right', 'total', 'total'};
%     devices = {'control', 'keeogo', 'control', 'keeogo', 'control', 'keeogo'};
% 
%     data = cell(length(conditions), 3);
%     for i = 1:length(conditions)
%         mean_value = metrics.(devices{i}).(sides{i}).(param_name).mean;
%         std_value = metrics.(devices{i}).(sides{i}).(param_name).std;
%         data{i, 1} = [conditions{i} ' ' strrep(param_name, '_', ' ')];
%         data{i, 2} = mean_value;
%         data{i, 3} = std_value;
%     end
% 
%     tbl = cell2table(data, "VariableNames", {'Condition', 'Mean', 'STD'});
% end

% %%
% 
% parameters = {'stride_length', 'stride_time', 'stance_time', 'swing_time', ...
%     'stance_percent', 'swing_percent', 'toe_angle', 'step_width', 'step_length', 'single_support', 'speed'};
% 
% for parameter = parameters
%     gait_parameters_combined = createTable(gait_parameters_combined, gait_metrics_mean, parameter);
% end
% 
% function gait_parameters_combined = createTable(gait_parameters_combined, gait_metrics_mean, parameter)
%     conditions = {'Control Left', 'Keeogo Left', 'Control Right', 'Keeogo Right', 'Total Control', 'Total Keeogo'};
%     gait_parameters_combined.(parameter) = cell2table(cellfun(@(x) {sprintf('%s %s', x, parameter), ...
%         gait_metrics_mean.(lower(strsplit(x, ' '){2})).(lower(strsplit(x, ' '){1})).(parameter).mean, ...
%         gait_metrics_mean.(lower(strsplit(x, ' '){2})).(lower(strsplit(x, ' '){1})).(parameter).std}, conditions), ...
%         "VariableNames", {'Condition', 'Mean', 'STD'});
% end

%% Add Values into a table
%% Stride Length
gait_parameters_combined.stride_length = {'Control Left Stride',gait_metrics_mean.control.left.stride_length.mean, gait_metrics_mean.control.left.stride_length.std;...
    'Keeogo Left Stride',gait_metrics_mean.keeogo.left.stride_length.mean, gait_metrics_mean.keeogo.left.stride_length.std;...
    'Control Right Stride',gait_metrics_mean.control.right.stride_length.mean, gait_metrics_mean.control.right.stride_length.std;...
    'Keeogo Right Stride',gait_metrics_mean.keeogo.right.stride_length.mean, gait_metrics_mean.keeogo.right.stride_length.std;...
    'Total Control', gait_metrics_mean.control.total.stride_length.mean, gait_metrics_mean.control.total.stride_length.std;...
    'Total Keeogo', gait_metrics_mean.keeogo.total.stride_length.mean, gait_metrics_mean.keeogo.total.stride_length.std};
gait_parameters_combined.stride_length = cell2table(gait_parameters_combined.stride_length,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.stride_time = {'Control Left Stride Time',gait_metrics_mean.control.left.stride_time.mean, gait_metrics_mean.control.left.stride_time.std;...
    'Keeogo Left Stride',gait_metrics_mean.keeogo.left.stride_time.mean, gait_metrics_mean.keeogo.left.stride_time.std;...
    'Control Right Stride',gait_metrics_mean.control.right.stride_time.mean, gait_metrics_mean.control.right.stride_time.std;...
    'Keeogo Right Stride',gait_metrics_mean.keeogo.right.stride_time.mean, gait_metrics_mean.keeogo.right.stride_time.std;...
    'Total Control', gait_metrics_mean.control.total.stride_time.mean, gait_metrics_mean.control.total.stride_time.std;...
    'Total Keeogo', gait_metrics_mean.keeogo.total.stride_time.mean, gait_metrics_mean.keeogo.total.stride_time.std};
gait_parameters_combined.stride_time = cell2table(gait_parameters_combined.stride_time,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.stance_time = {'Control Left Stance Time',gait_metrics_mean.control.left.stancetime.mean, gait_metrics_mean.control.left.stancetime.std;...
    'Keeogo Left Stance Time',gait_metrics_mean.keeogo.left.stancetime.mean, gait_metrics_mean.keeogo.left.stancetime.std;...
    'Control Right Stance Time',gait_metrics_mean.control.right.stancetime.mean, gait_metrics_mean.control.right.stancetime.std;...
    'Keeogo Right Stance Time',gait_metrics_mean.keeogo.right.stancetime.mean, gait_metrics_mean.keeogo.right.stancetime.std;...
    'Total Control Stance Time', gait_metrics_mean.control.total.stancetime.mean, gait_metrics_mean.control.total.stancetime.std;...
    'Total Keeogo Stance Time', gait_metrics_mean.keeogo.total.stancetime.mean, gait_metrics_mean.keeogo.total.stancetime.std};
gait_parameters_combined.stance_time = cell2table(gait_parameters_combined.stance_time,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.swing_time = {'Control Left Swing Time',gait_metrics_mean.control.left.swingtime.mean, gait_metrics_mean.control.left.swingtime.std;...
    'Keeogo Left Swing Time',gait_metrics_mean.keeogo.left.swingtime.mean, gait_metrics_mean.keeogo.left.swingtime.std;...
    'Control Right Swing Time',gait_metrics_mean.control.right.swingtime.mean, gait_metrics_mean.control.right.swingtime.std;...
    'Keeogo Right Swing Time',gait_metrics_mean.keeogo.right.swingtime.mean, gait_metrics_mean.keeogo.right.swingtime.std;...
    'Total Control Swing Time', gait_metrics_mean.control.total.swingtime.mean, gait_metrics_mean.control.total.swingtime.std;...
    'Total Keeogo Swing Time', gait_metrics_mean.keeogo.total.swingtime.mean, gait_metrics_mean.keeogo.total.swingtime.std};
gait_parameters_combined.swing_time = cell2table(gait_parameters_combined.swing_time,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.stance_percent = {'Control Left Stance Percent',gait_metrics_mean.control.left.stance_perc.mean, gait_metrics_mean.control.left.stance_perc.std;...
    'Keeogo Left Stance Percent',gait_metrics_mean.keeogo.left.stance_perc.mean, gait_metrics_mean.keeogo.left.stance_perc.std;...
    'Control Right Stance Percent',gait_metrics_mean.control.right.stance_perc.mean, gait_metrics_mean.control.right.stance_perc.std;...
    'Keeogo Right Stance Percent',gait_metrics_mean.keeogo.right.stance_perc.mean, gait_metrics_mean.keeogo.right.stance_perc.std;...
    'Total Control Stance Percent', gait_metrics_mean.control.total.stance_perc.mean, gait_metrics_mean.control.total.stance_perc.std;...
    'Total Keeogo Stance Percent', gait_metrics_mean.keeogo.total.stance_perc.mean, gait_metrics_mean.keeogo.total.stance_perc.std};
gait_parameters_combined.stance_percent = cell2table(gait_parameters_combined.stance_percent,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.swing_percent = {'Control Left Swing Percent',gait_metrics_mean.control.left.swing_perc.mean, gait_metrics_mean.control.left.swing_perc.std;...
    'Keeogo Left Swing Percent',gait_metrics_mean.keeogo.left.swing_perc.mean, gait_metrics_mean.keeogo.left.swing_perc.std;...
    'Control Right Swing Percent',gait_metrics_mean.control.right.swing_perc.mean, gait_metrics_mean.control.right.swing_perc.std;...
    'Keeogo Right Swing Percent',gait_metrics_mean.keeogo.right.swing_perc.mean, gait_metrics_mean.keeogo.right.swing_perc.std;...
    'Total Control Swing Percent', gait_metrics_mean.control.total.swing_perc.mean, gait_metrics_mean.control.total.swing_perc.std;...
    'Total Keeogo Swing Percent', gait_metrics_mean.keeogo.total.swing_perc.mean, gait_metrics_mean.keeogo.total.swing_perc.std};
gait_parameters_combined.swing_percent = cell2table(gait_parameters_combined.swing_percent,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.toe_angle = {'Control Left Toe Angle',gait_metrics_mean.control.left.toe_out.mean, gait_metrics_mean.control.left.toe_out.std;...
    'Keeogo Left Toe Angle',gait_metrics_mean.keeogo.left.toe_out.mean, gait_metrics_mean.keeogo.left.toe_out.std;...
    'Control Right Toe Angle',gait_metrics_mean.control.right.toe_out.mean, gait_metrics_mean.control.right.toe_out.std;...
    'Keeogo Right Toe Angle',gait_metrics_mean.keeogo.right.toe_out.mean, gait_metrics_mean.keeogo.right.toe_out.std;...
    'Total Control Toe Angle', gait_metrics_mean.control.total.toe_out.mean, gait_metrics_mean.control.total.toe_out.std;...
    'Total Keeogo Toe Angle', gait_metrics_mean.keeogo.total.toe_out.mean, gait_metrics_mean.keeogo.total.toe_out.std};
gait_parameters_combined.toe_angle = cell2table(gait_parameters_combined.toe_angle,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.step_width = {'Control Left Step Width',gait_metrics_mean.control.left.step_width.mean, gait_metrics_mean.control.left.step_width.std;...
    'Keeogo Left Step Width',gait_metrics_mean.keeogo.left.step_width.mean, gait_metrics_mean.keeogo.left.step_width.std;...
    'Control Right Step Width',gait_metrics_mean.control.right.step_width.mean, gait_metrics_mean.control.right.step_width.std;...
    'Keeogo Right Step Width',gait_metrics_mean.keeogo.right.step_width.mean, gait_metrics_mean.keeogo.right.step_width.std;...
    'Total Control Step Width', gait_metrics_mean.control.total.step_width.mean, gait_metrics_mean.control.total.step_width.std;...
    'Total Keeogo Step Width', gait_metrics_mean.keeogo.total.step_width.mean, gait_metrics_mean.keeogo.total.step_width.std};
gait_parameters_combined.step_width = cell2table(gait_parameters_combined.step_width,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.step_length = {'Control Left Step Length',gait_metrics_mean.control.left.step_length.mean, gait_metrics_mean.control.left.step_length.std;...
    'Keeogo Left Step Length',gait_metrics_mean.keeogo.left.step_length.mean, gait_metrics_mean.keeogo.left.step_length.std;...
    'Control Right Step Length',gait_metrics_mean.control.right.step_length.mean, gait_metrics_mean.control.right.step_length.std;...
    'Keeogo Right Step Length',gait_metrics_mean.keeogo.right.step_length.mean, gait_metrics_mean.keeogo.right.step_length.std;...
    'Total Control Step Length', gait_metrics_mean.control.total.step_length.mean, gait_metrics_mean.control.total.step_length.std;...
    'Total Keeogo Step Length', gait_metrics_mean.keeogo.total.step_length.mean, gait_metrics_mean.keeogo.total.step_length.std};
gait_parameters_combined.step_length = cell2table(gait_parameters_combined.step_length,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.single_support = {'Control Left Single Support',gait_metrics_mean.control.left.single_support.mean, gait_metrics_mean.control.left.single_support.std;...
    'Keeogo Left Single Support',gait_metrics_mean.keeogo.left.single_support.mean, gait_metrics_mean.keeogo.left.single_support.std;...
    'Control Right Single Support',gait_metrics_mean.control.right.single_support.mean, gait_metrics_mean.control.right.single_support.std;...
    'Keeogo Right Single Support',gait_metrics_mean.keeogo.right.single_support.mean, gait_metrics_mean.keeogo.right.single_support.std;...
    'Total Control Single Support', gait_metrics_mean.control.total.single_support.mean, gait_metrics_mean.control.total.single_support.std;...
    'Total Keeogo Single Support', gait_metrics_mean.keeogo.total.single_support.mean, gait_metrics_mean.keeogo.total.single_support.std};
gait_parameters_combined.single_support = cell2table(gait_parameters_combined.single_support,"VariableNames",{'Condition','Mean','STD'});

gait_parameters_combined.speed = {'Control Speed',gait_metrics_mean.control.total.speed.mean, gait_metrics_mean.control.total.speed.std;...
    'Keeogo Speed',gait_metrics_mean.keeogo.total.speed.mean, gait_metrics_mean.keeogo.total.speed.std};
gait_parameters_combined.speed = cell2table(gait_parameters_combined.speed,"VariableNames",{'Condition','Mean','STD'});
% %% CCI
% %loading Stance
% loading_stance.CCI = {'Control Left Loading CCI',gait_emg_metrics_combined1_rms.control.CCI_l_loading_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_loading_rms.std;...
%     'Keeogo Left Loading CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_loading_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_loading_rms.std;...
%     'Control Right Loading CCI',gait_emg_metrics_combined1_rms.control.CCI_r_loading_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_loading_rms.std;...
%     'Keeogo Right Loading CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_loading_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_loading_rms.std};
% loading_stance.CCI = cell2table(loading_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %Early Stance
% early_stance.CCI = {'Control Left Early CCI',gait_emg_metrics_combined1_rms.control.CCI_l_early_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_early_rms.std;...
%     'Keeogo Left Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_early_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_early_rms.std;...
%     'Control Right Early CCI',gait_emg_metrics_combined1_rms.control.CCI_r_early_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_early_rms.std;...
%     'Keeogo Right Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_early_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_early_rms.std};
% early_stance.CCI = cell2table(early_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %Mid Stance
% mid_stance.CCI = {'Control Left Early CCI',gait_emg_metrics_combined1_rms.control.CCI_l_mid_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_mid_rms.std;...
%     'Keeogo Left Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_mid_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_mid_rms.std;...
%     'Control Right Early CCI',gait_emg_metrics_combined1_rms.control.CCI_r_mid_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_mid_rms.std;...
%     'Keeogo Right Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_mid_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_mid_rms.std};
% mid_stance.CCI = cell2table(mid_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %Late Stance
% late_stance.CCI = {'Control Left Early CCI',gait_emg_metrics_combined1_rms.control.CCI_l_late_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_l_late_rms.std;...
%     'Keeogo Left Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_l_late_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_l_late_rms.std;...
%     'Control Right Early CCI',gait_emg_metrics_combined1_rms.control.CCI_r_late_rms.mean,gait_emg_metrics_combined1_rms.control.CCI_r_late_rms.std;...
%     'Keeogo Right Early CCI',gait_emg_metrics_combined1_rms.keeogo.CCI_r_late_rms.mean,gait_emg_metrics_combined1_rms.keeogo.CCI_r_late_rms.std};
% late_stance.CCI = cell2table(late_stance.CCI,"VariableNames",{'Condition','Mean','STD'});
% 
% %% CCR Zero
% %loading Stance
% loading_stance.CCR = {'Control Left Loading CCI',gait_emg_metrics_combined1.control.CCR_zero_l_loading.mean,gait_emg_metrics_combined1.control.CCR_zero_l_loading.std;...
%     'Keeogo Left Loading CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_loading.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_loading.std;...
%     'Control Right Loading CCI',gait_emg_metrics_combined1.control.CCR_zero_r_loading.mean,gait_emg_metrics_combined1.control.CCR_zero_r_loading.std;...
%     'Keeogo Right Loading CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_loading.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_loading.std};
% loading_stance.CCR = cell2table(loading_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %Early Stance
% early_stance.CCR = {'Control Left Early CCI',gait_emg_metrics_combined1.control.CCR_zero_l_early.mean,gait_emg_metrics_combined1.control.CCR_zero_l_early.std;...
%     'Keeogo Left Early CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_early.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_early.std;...
%     'Control Right Early CCI',gait_emg_metrics_combined1.control.CCR_zero_r_early.mean,gait_emg_metrics_combined1.control.CCR_zero_r_early.std;...
%     'Keeogo Right Early CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_early.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_early.std};
% early_stance.CCR = cell2table(early_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %Mid Stance
% mid_stance.CCR = {'Control Left Mid CCI',gait_emg_metrics_combined1.control.CCR_zero_l_mid.mean,gait_emg_metrics_combined1.control.CCR_zero_l_mid.std;...
%     'Keeogo Left Mid CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_mid.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_mid.std;...
%     'Control Right Mid CCI',gait_emg_metrics_combined1.control.CCR_zero_r_mid.mean,gait_emg_metrics_combined1.control.CCR_zero_r_mid.std;...
%     'Keeogo Right Mid CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_mid.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_mid.std};
% mid_stance.CCR = cell2table(mid_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %Late Stance
% late_stance.CCR = {'Control Left Late CCI',gait_emg_metrics_combined1.control.CCR_zero_l_late.mean,gait_emg_metrics_combined1.control.CCR_zero_l_late.std;...
%     'Keeogo Left Late CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_l_late.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_l_late.std;...
%     'Control Right Late CCI',gait_emg_metrics_combined1.control.CCR_zero_r_late.mean,gait_emg_metrics_combined1.control.CCR_zero_r_late.std;...
%     'Keeogo Right Late CCI',gait_emg_metrics_combined1.keeogo.CCR_zero_r_late.mean,gait_emg_metrics_combined1.keeogo.CCR_zero_r_late.std};
% late_stance.CCR = cell2table(late_stance.CCR,"VariableNames",{'Condition','Mean','STD'});
% 
% %% Swing
% %Swing Full
% swing.full_quadriceps =  {'Control Left Quadricep Swing',gait_emg_swing_metrics_combined.control.lquad_swing.mean,gait_emg_swing_metrics_combined.control.lquad_swing.std;...
%     'Keeogo Left Quadricep Swing',gait_emg_swing_metrics_combined.keeogo.lquad_swing.mean,gait_emg_swing_metrics_combined.keeogo.lquad_swing.std;...
%     'Control Right Quadricep Swing',gait_emg_swing_metrics_combined.control.rquad_swing.mean,gait_emg_swing_metrics_combined.control.rquad_swing.std;...
%     'Keeogo Right Quadricep Swing',gait_emg_swing_metrics_combined.keeogo.rquad_swing.mean,gait_emg_swing_metrics_combined.keeogo.rquad_swing.std};
% swing.full_quadriceps = cell2table(swing.full_quadriceps,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.full_hamstrings =  {'Control Left Hamstring Swing',gait_emg_swing_metrics_combined.control.lham_swing.mean,gait_emg_swing_metrics_combined.control.lham_swing.std;...
%     'Keeogo Left Hamstring Swing',gait_emg_swing_metrics_combined.keeogo.lham_swing.mean,gait_emg_swing_metrics_combined.keeogo.lham_swing.std;...
%     'Control Right Hamstring Swing',gait_emg_swing_metrics_combined.control.rham_swing.mean,gait_emg_swing_metrics_combined.control.rham_swing.std;...
%     'Keeogo Right Hamstring Swing',gait_emg_swing_metrics_combined.keeogo.rham_swing.mean,gait_emg_swing_metrics_combined.keeogo.rham_swing.std};
% swing.full_hamstrings = cell2table(swing.full_hamstrings,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.full_gastrocnemius =  {'Control Left Gastrocnemius Swing',gait_emg_swing_metrics_combined.control.lgas_swing.mean,gait_emg_swing_metrics_combined.control.lgas_swing.std;...
%     'Keeogo Left Gastrocnemius Swing',gait_emg_swing_metrics_combined.keeogo.lgas_swing.mean,gait_emg_swing_metrics_combined.keeogo.lgas_swing.std;...
%     'Control Right Gastrocnemius Swing',gait_emg_swing_metrics_combined.control.rgas_swing.mean,gait_emg_swing_metrics_combined.control.rgas_swing.std;...
%     'Keeogo Right Gastrocnemius Swing',gait_emg_swing_metrics_combined.keeogo.rgas_swing.mean,gait_emg_swing_metrics_combined.keeogo.rgas_swing.std};
% swing.full_gastrocnemius = cell2table(swing.full_gastrocnemius,"VariableNames",{'Condition','Mean','STD'});
% 
% % Swing Prep
% swing.prep_quadriceps =  {'Control Left Quadricep Prep Swing',gait_emg_swing_metrics_combined.control.lquad_stride_prep.mean,gait_emg_swing_metrics_combined.control.lquad_stride_prep.std;...
%     'Keeogo Left Quadricep Prep Swing',gait_emg_swing_metrics_combined.keeogo.lquad_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.lquad_stride_prep.std;...
%     'Control Right Quadricep Prep Swing',gait_emg_swing_metrics_combined.control.rquad_stride_prep.mean,gait_emg_swing_metrics_combined.control.rquad_stride_prep.std;...
%     'Keeogo Right Quadricep Prep Swing',gait_emg_swing_metrics_combined.keeogo.rquad_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.rquad_stride_prep.std};
% swing.prep_quadriceps = cell2table(swing.prep_quadriceps,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.prep_hamstrings =  {'Control Left Hamstring Prep Swing',gait_emg_swing_metrics_combined.control.lham_stride_prep.mean,gait_emg_swing_metrics_combined.control.lham_stride_prep.std;...
%     'Keeogo Left Hamstring Prep Swing',gait_emg_swing_metrics_combined.keeogo.lham_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.lham_stride_prep.std;...
%     'Control Right Hamstring Prep Swing',gait_emg_swing_metrics_combined.control.rham_stride_prep.mean,gait_emg_swing_metrics_combined.control.rham_stride_prep.std;...
%     'Keeogo Right Hamstring Prep Swing',gait_emg_swing_metrics_combined.keeogo.rham_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.rham_stride_prep.std};
% swing.prep_hamstrings = cell2table(swing.prep_hamstrings,"VariableNames",{'Condition','Mean','STD'});
% 
% swing.prep_gastrocnemius =  {'Control Left Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.control.lgas_stride_prep.mean,gait_emg_swing_metrics_combined.control.lgas_stride_prep.std;...
%     'Keeogo Left Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.keeogo.lgas_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.lgas_stride_prep.std;...
%     'Control Right Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.control.rgas_stride_prep.mean,gait_emg_swing_metrics_combined.control.rgas_stride_prep.std;...
%     'Keeogo Right Gastrocnemius Prep Swing',gait_emg_swing_metrics_combined.keeogo.rgas_stride_prep.mean,gait_emg_swing_metrics_combined.keeogo.rgas_stride_prep.std};
% swing.prep_gastrocnemius = cell2table(swing.prep_gastrocnemius,"VariableNames",{'Condition','Mean','STD'});
%% Range of motion
ROM = {'Control ROM Left', main_parameters_mean.control.left.swing_rom.mean, main_parameters_mean.control.left.swing_rom.std;...
    'Keeogo ROM Left', main_parameters_mean.keeogo.left.swing_rom.mean, main_parameters_mean.keeogo.left.swing_rom.std;...
    'Control ROM Right', main_parameters_mean.control.right.swing_rom.mean, main_parameters_mean.control.right.swing_rom.std;...
    'Keeogo ROM Right', main_parameters_mean.keeogo.right.swing_rom.mean, main_parameters_mean.keeogo.right.swing_rom.std};
ROM = cell2table(ROM,"VariableNames",{'Condition','Mean','STD'});
%% Moments
%loading Stance
loading_stance.flexion = {'Control Left Loading Flexion',main_parameters_mean.control.left.loading_stance.flexion.mean, main_parameters_mean.control.left.loading_stance.flexion.std;...
    'Keeogo Left Loading Flexion',main_parameters_mean.keeogo.left.loading_stance.flexion.mean, main_parameters_mean.keeogo.left.loading_stance.flexion.std;...
    'Control Right Loading Flexion',main_parameters_mean.control.right.loading_stance.flexion.mean, main_parameters_mean.control.right.loading_stance.flexion.std;...
    'Keeogo Right Loading Flexion',main_parameters_mean.keeogo.right.loading_stance.flexion.mean, main_parameters_mean.keeogo.right.loading_stance.flexion.std};
loading_stance.flexion = cell2table(loading_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

loading_stance.adduction = {'Control Left Loading Adduction',main_parameters_mean.control.left.loading_stance.adduction.mean,main_parameters_mean.control.left.loading_stance.adduction.std;...
    'Keeogo Left Loading Adduction',main_parameters_mean.keeogo.left.loading_stance.adduction.mean,main_parameters_mean.keeogo.left.loading_stance.adduction.std;...
    'Control Right Loading Adduction',main_parameters_mean.control.right.loading_stance.adduction.mean, main_parameters_mean.control.right.loading_stance.adduction.std;...
    'Keeogo Right Loading Adduction',main_parameters_mean.keeogo.right.loading_stance.adduction.mean, main_parameters_mean.keeogo.right.loading_stance.adduction.std};
loading_stance.adduction = cell2table(loading_stance.adduction,"VariableNames",{'Condition','Mean','STD'});
%early Stance
early_stance.flexion = {'Control Left Early Flexion', main_parameters_mean.control.left.early_stance.flexion.mean,main_parameters_mean.control.left.early_stance.flexion.std;...
    'Keeogo Left Early Flexion', main_parameters_mean.keeogo.left.early_stance.flexion.mean, main_parameters_mean.keeogo.left.early_stance.flexion.std;...
    'Control Right Early Flexion', main_parameters_mean.control.right.early_stance.flexion.mean,main_parameters_mean.control.right.early_stance.flexion.std;...
    'Keeogo Right Early Flexion', main_parameters_mean.keeogo.right.early_stance.flexion.mean, main_parameters_mean.keeogo.right.early_stance.flexion.std};
early_stance.flexion = cell2table(early_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

early_stance.adduction = {'Control Left Early Adduction', main_parameters_mean.control.left.early_stance.adduction.mean,main_parameters_mean.control.left.early_stance.adduction.std;...
    'Keeogo Left Early Adduction', main_parameters_mean.keeogo.left.early_stance.adduction.mean, main_parameters_mean.keeogo.left.early_stance.adduction.std;...
    'Control Right Early Adduction', main_parameters_mean.control.right.early_stance.adduction.mean,main_parameters_mean.control.right.early_stance.adduction.std;...
    'Keeogo Right Early Adduction', main_parameters_mean.keeogo.right.early_stance.adduction.mean, main_parameters_mean.keeogo.right.early_stance.adduction.std};
early_stance.adduction = cell2table(early_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%Mid-stance 
mid_stance.flexion = {'Control Left Mid Flexion', main_parameters_mean.control.left.mid_stance.flexion.mean,main_parameters_mean.control.left.mid_stance.flexion.std;...
    'Keeogo Left Mid Flexion', main_parameters_mean.keeogo.left.mid_stance.flexion.mean, main_parameters_mean.keeogo.left.mid_stance.flexion.std;...
    'Control Right Mid Flexion', main_parameters_mean.control.right.mid_stance.flexion.mean,main_parameters_mean.control.right.mid_stance.flexion.std;...
    'Keeogo Right Mid Flexion', main_parameters_mean.keeogo.right.mid_stance.flexion.mean, main_parameters_mean.keeogo.right.mid_stance.flexion.std};
mid_stance.flexion = cell2table(mid_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

mid_stance.adduction = {'Control Left Mid Adduction',main_parameters_mean.control.left.mid_stance.adduction.mean,main_parameters_mean.control.left.mid_stance.adduction.std;...
    'Keeogo Left Mid Adduction',main_parameters_mean.keeogo.left.mid_stance.adduction.mean, main_parameters_mean.keeogo.left.mid_stance.adduction.std;...
    'Control Right Mid Adduction',main_parameters_mean.control.right.mid_stance.adduction.mean,main_parameters_mean.control.right.mid_stance.adduction.std;...
    'Keeogo Right Mid Adduction',main_parameters_mean.keeogo.right.mid_stance.adduction.mean, main_parameters_mean.keeogo.right.mid_stance.adduction.std};
mid_stance.adduction = cell2table(mid_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%late Stance
late_stance.flexion = {'Control Left Late Flexion',main_parameters_mean.control.left.late_stance.flexion.mean,main_parameters_mean.control.left.late_stance.flexion.std;...
    'Keeogo Left Late Flexion',main_parameters_mean.keeogo.left.late_stance.flexion.mean, main_parameters_mean.keeogo.left.late_stance.flexion.std;...
    'Control Right Late Flexion', main_parameters_mean.control.right.late_stance.flexion.mean,main_parameters_mean.control.right.late_stance.flexion.std;...
    'Keeogo Right Late Flexion',main_parameters_mean.keeogo.right.late_stance.flexion.mean, main_parameters_mean.keeogo.right.late_stance.flexion.std};
late_stance.flexion = cell2table(late_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

late_stance.adduction = {'Control Left Late Adduction',main_parameters_mean.control.left.late_stance.adduction.mean,main_parameters_mean.control.left.late_stance.adduction.std;...
    'Keeogo Left Late Adduction',main_parameters_mean.keeogo.left.late_stance.adduction.mean, main_parameters_mean.keeogo.left.late_stance.adduction.std;...
    'Control Right Late Adduction',main_parameters_mean.control.right.late_stance.adduction.mean, main_parameters_mean.control.right.late_stance.adduction.std;...
    'Keeogo Right Late Adduction',main_parameters_mean.keeogo.right.late_stance.adduction.mean, main_parameters_mean.keeogo.right.late_stance.adduction.std};
late_stance.adduction = cell2table(late_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%full Stance
full_stance.flexion = {'Control Left Full Flexion',main_parameters_mean.control.left.full_stance.flexion.mean,main_parameters_mean.control.left.full_stance.flexion.std;...
    'Keeogo Left Full Flexion',main_parameters_mean.keeogo.left.full_stance.flexion.mean, main_parameters_mean.keeogo.left.full_stance.flexion.std;...
    'Control Right Full Flexion',main_parameters_mean.control.right.full_stance.flexion.mean,main_parameters_mean.control.right.full_stance.flexion.std;...
    'Keeogo Right Full Flexion',main_parameters_mean.keeogo.right.full_stance.flexion.mean, main_parameters_mean.keeogo.right.full_stance.flexion.std};
full_stance.flexion = cell2table(full_stance.flexion,"VariableNames",{'Condition','Mean','STD'});

full_stance.adduction = {'Control Left Full Adduction',main_parameters_mean.control.left.full_stance.adduction.mean,main_parameters_mean.control.left.full_stance.adduction.std;...
    'Keeogo Left Full Adduction', main_parameters_mean.keeogo.left.full_stance.adduction.mean, main_parameters_mean.keeogo.left.full_stance.adduction.std;...
    'Control Right Full Adduction', main_parameters_mean.control.right.full_stance.adduction.mean, main_parameters_mean.control.right.full_stance.adduction.std;...
    'Keeogo Right Full Adduction', main_parameters_mean.keeogo.right.full_stance.adduction.mean, main_parameters_mean.keeogo.right.full_stance.adduction.std};
full_stance.adduction = cell2table(full_stance.adduction,"VariableNames",{'Condition','Mean','STD'});

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% File name
file_name = 'stats_analysis_'+ participant_number +'.xlsx';
%% Stride Length
writetable(gait_parameters_combined.stride_length,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B1');
writetable(gait_parameters_combined.stride_time,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B8');
writetable(gait_parameters_combined.stance_time,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B15');
writetable(gait_parameters_combined.swing_time,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B22');
writetable(gait_parameters_combined.stance_percent,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B29');
writetable(gait_parameters_combined.swing_percent,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B36');
writetable(gait_parameters_combined.toe_angle,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B43');
writetable(gait_parameters_combined.step_width,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B50');
writetable(gait_parameters_combined.step_length,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B57');
writetable(gait_parameters_combined.single_support,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B64');
writetable(gait_parameters_combined.speed,file_name,'Sheet','Gait Parameters','WriteVariableNames',true,'Range','B71');
%% ROM
writetable(ROM,file_name,'Sheet','ROM','WriteVariableNames',true,'Range','B1');

% %% CCI
% writetable(loading_stance.CCI,file_name,'Sheet','CCI','WriteVariableNames',true,'Range','B1')
% writetable(early_stance.CCI,file_name,'Sheet','CCI','WriteVariableNames',true,'Range','B6')
% writetable(mid_stance.CCI,file_name,'Sheet','CCI','WriteVariableNames',true,'Range','B11')
% writetable(late_stance.CCI,file_name,'Sheet','CCI','WriteVariableNames',true,'Range','B16')
% %% CCR
% writetable(loading_stance.CCR,file_name,'Sheet','CCR','WriteVariableNames',true,'Range','B1')
% writetable(early_stance.CCR,file_name,'Sheet','CCR','WriteVariableNames',true,'Range','B6')
% writetable(mid_stance.CCR,file_name,'Sheet','CCR','WriteVariableNames',true,'Range','B11')
% writetable(late_stance.CCR,file_name,'Sheet','CCR','WriteVariableNames',true,'Range','B16')
% %% Swing
% writetable(swing.full_quadriceps,file_name,'Sheet','Swing_Full','WriteVariableNames',true,'Range','B1')
% writetable(swing.full_hamstring,file_name,'Sheet','Swing_Full','WriteVariableNames',true,'Range','B6')
% writetable(swing.full_gastrocnemius,file_name,'Sheet','Swing_Full','WriteVariableNames',true,'Range','B11')
% writetable(swing.prep_quadriceps,file_name,'Sheet','Swing_Prep','WriteVariableNames',true,'Range','B16')
% writetable(swing.prep_hamstring,file_name,'Sheet','Swing_Prep','WriteVariableNames',true,'Range','B21')
% writetable(swing.prep_gastrocnemius,file_name,'Sheet','Swing_Prep','WriteVariableNames',true,'Range','B26')
%% Moments (Flexion)
%Loading
writetable(loading_stance.flexion,file_name,'Sheet','Loading_Flexion','WriteVariableNames',true,'Range','B1');
%Early
writetable(early_stance.flexion,file_name,'Sheet','Early_Flexion','WriteVariableNames',true,'Range','B1');
%Mid
writetable(mid_stance.flexion,file_name,'Sheet','Mid_Flexion','WriteVariableNames',true,'Range','B1');

%Late
writetable(late_stance.flexion,file_name,'Sheet','Late_Flexion','WriteVariableNames',true,'Range','B1');

%Full
writetable(full_stance.flexion,file_name,'Sheet','Full_Flexion','WriteVariableNames',true,'Range','B1');

%% Moments (Adduction)
%Loading
writetable(loading_stance.adduction,file_name,'Sheet','Loading_Adduction','WriteVariableNames',true,'Range','B1');

%Early
writetable(early_stance.adduction,file_name,'Sheet','Early_Adduction','WriteVariableNames',true,'Range','B1');

%Mid
writetable(mid_stance.adduction,file_name,'Sheet','Mid_Adduction','WriteVariableNames',true,'Range','B1');

%Late
writetable(late_stance.adduction,file_name,'Sheet','Late_Adduction','WriteVariableNames',true,'Range','B1');

%Full
writetable(full_stance.adduction,file_name,'Sheet','Full_Adduction','WriteVariableNames',true,'Range','B1');

end